pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/manoharch127/devops-monitoring-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t cloudops-dashboard -f docker/Dockerfile .'
            }
        }

        stage('Stop Existing Container') {
            steps {
                sh '''
                docker stop dashboard || true
                docker rm dashboard || true
                '''
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker run -d -p 5000:5000 \
                --name dashboard \
                cloudops-dashboard
                '''
            }
        }
    }
}
